const state={snapshot:null,selectedToken:null,settingsDirty:false,pending:new Set()};
const sliders=[
  ['damageMultiplier','Hasar','×',0,100,.25],['playerSpeedMultiplier','Oyuncu hızı','×',.25,2.5,.05],
  ['gearDropMultiplier','Gear oranı','×',0,100,.25],['materialDropMultiplier','Material oranı','×',0,100,.25],
  ['goldMultiplier','Gold','×',0,100,.25],['xpMultiplier','XP','×',0,100,.25]
];
const $=id=>document.getElementById(id);
function toast(message,error=false){const el=$('toast');el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3200)}
async function api(path,options={}){const response=await fetch(`/api/${path}`,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({error:'Geçersiz sunucu yanıtı'}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function element(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!=null)node.textContent=text;return node}
function initSliders(){const root=$('sliders');for(const [id,label,unit,min,max,step] of sliders){const wrapper=element('label','slider');wrapper.htmlFor=id;const head=element('div','slider-head');head.append(element('span','',label));const output=element('output','',`1${unit}`);output.id=`${id}Out`;output.htmlFor=id;head.append(output);const input=element('input');Object.assign(input,{id,type:'range',min,max,step,value:1});wrapper.append(head,input);root.append(wrapper);input.addEventListener('input',()=>{updateSliderOutput(id,unit);state.settingsDirty=true})}}
function updateSliderOutput(id,unit){const value=Number($(id).value);$(`${id}Out`).textContent=`${value.toFixed(value%1?2:0)}${unit}`}
function initMetrics(){const labels=[['Çevrimiçi Oyuncu','Aktif oturum'],['Aktif Oda','Canlı örnek'],['Bağlantı','Açık soket'],['Sunucu Süresi','Kesintisiz']];for(const [index,[label,note]] of labels.entries()){const metric=element('div','metric');metric.dataset.metric=String(index);const top=element('div','metric-top');top.append(element('span','',label),element('span','metric-icon','●'));metric.append(top,element('b','metric-value','0'));const foot=element('span','metric-foot');foot.append(element('i'),document.createTextNode(note));metric.append(foot);$('metrics').append(metric)}}
function updateKeyedList(root,items,keyOf,create,update){const wanted=new Set(items.map(item=>String(keyOf(item))));let restoreFocus=false;for(const child of [...root.children])if(!wanted.has(child.dataset.key)){restoreFocus=restoreFocus||child===document.activeElement;child.remove()}for(const item of items){const key=String(keyOf(item));let child=[...root.children].find(node=>node.dataset.key===key);if(!child){child=create(item);child.dataset.key=key;root.append(child)}update(child,item)}if(restoreFocus)(root.querySelector('[aria-pressed="true"]')||root.querySelector('button'))?.focus()}
function createPlayer(){const button=element('button','player');button.type='button';button.append(element('span','avatar'),element('span','player-copy'),element('span','hp'));button.addEventListener('click',()=>{state.selectedToken=Number(button.dataset.token);updatePlayerSelection();updateTarget()});return button}
function updatePlayer(button,player){button.dataset.token=String(player.token);button.setAttribute('aria-pressed',String(player.token===state.selectedToken));button.classList.toggle('selected',player.token===state.selectedToken);button.querySelector('.avatar').textContent=player.name.slice(0,1).toUpperCase()||'?';const copy=button.querySelector('.player-copy');let name=copy.querySelector('b');let detail=copy.querySelector('small');if(!name){name=element('b');detail=element('small');copy.append(name,detail)}name.textContent=player.name;detail.textContent=`${player.level} · Oda ${player.roomId}`;button.querySelector('.hp').textContent=`${player.hp}/${player.maxHp} HP`;button.setAttribute('aria-label',`${player.name}, ${player.level}, oda ${player.roomId}, ${player.hp}/${player.maxHp} HP`)}
function createRoom(){const room=element('div','room');room.append(element('div','room-top'),element('div','room-stats'));return room}
function updateRoom(room,data){const top=room.querySelector('.room-top');top.replaceChildren();const copy=element('span');copy.append(element('b','',data.level),element('small','',`Oda ${data.roomId}`));top.append(copy,element('span','badge badge-outline',`${data.players}P`));const stats=room.querySelector('.room-stats');stats.replaceChildren(element('span','',`☠ ${data.hostiles} düşman`),element('span','',`◉ ${data.players} oyuncu`))}
function updatePlayerSelection(){document.querySelectorAll('.player').forEach(button=>{const selected=Number(button.dataset.token)===state.selectedToken;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected))})}
function updateTarget(){const target=state.snapshot?.players.find(player=>player.token===state.selectedToken);$('targetName').textContent=target?target.name:'Oyuncu seçin';$('targetLocation').textContent=target?`${target.level} / ${target.roomId}`:'—';const summary=$('targetSummary');const avatar=element('div','target-avatar',target?(target.name.slice(0,1).toUpperCase()||'?'):'?');const copy=element('div');copy.append(element('strong','',target?target.name:'Oyuncu seçilmedi'),element('span','',target?`${target.hp}/${target.maxHp} HP · ${target.level} · Oda ${target.roomId}`:'Kontrol etmek için listeden bir oyuncu seçin.'));summary.replaceChildren(avatar,copy)}
function render(snapshot){state.snapshot=snapshot;if(state.selectedToken&&!snapshot.players.some(player=>player.token===state.selectedToken))state.selectedToken=null;if(!state.selectedToken&&snapshot.players.length)state.selectedToken=snapshot.players[0].token;$('liveDot').className='dot live';$('liveText').textContent='Canlı';$('lastUpdate').textContent=new Date(snapshot.generatedAt).toLocaleTimeString('tr-TR');const values=[snapshot.onlinePlayers,snapshot.rooms.length,snapshot.connections,formatUptime(snapshot.uptimeSeconds)];document.querySelectorAll('[data-metric]').forEach(metric=>metric.querySelector('.metric-value').textContent=values[Number(metric.dataset.metric)]);$('playerCount').textContent=`${snapshot.players.length} çevrimiçi`;$('navPlayerCount').textContent=snapshot.players.length;const players=$('players');players.className='player-list'+(snapshot.players.length?'':' empty-state');if(snapshot.players.length&&!players.children.length)players.textContent='';updateKeyedList(players,snapshot.players,player=>player.token,createPlayer,updatePlayer);if(!snapshot.players.length)players.textContent='Aktif oyuncu bekleniyor…';$('roomCount').textContent=`${snapshot.rooms.length} oda`;const rooms=$('rooms');rooms.className='room-list'+(snapshot.rooms.length?'':' empty-state');if(snapshot.rooms.length&&!rooms.children.length)rooms.textContent='';updateKeyedList(rooms,snapshot.rooms,room=>`${room.level}:${room.roomId}`,createRoom,updateRoom);if(!snapshot.rooms.length)rooms.textContent='Aktif oda bekleniyor…';updateTarget();if(!state.settingsDirty)syncSettings(snapshot.settings)}
function syncSettings(settings){['oneHitEnabled','godModeEnabled','freezeEnemies'].forEach(key=>$(key).checked=Boolean(settings[key]));sliders.forEach(([id,,unit])=>{$(id).value=settings[id];updateSliderOutput(id,unit)});state.settingsDirty=false}
function readSettings(){const payload={};['oneHitEnabled','godModeEnabled','freezeEnemies'].forEach(key=>payload[key]=$(key).checked);sliders.forEach(([id])=>payload[id]=Number($(id).value));return payload}
function formatUptime(seconds){const hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);return hours?`${hours} sa ${minutes} dk`:`${minutes} dk`}
function confirmAction(message,label='Onayla'){const dialog=$('confirmDialog');$('confirmMessage').textContent=message;$('confirmSubmit').textContent=label;dialog.returnValue='cancel';dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='confirm'),{once:true}))}
function setPending(key,pending){if(pending)state.pending.add(key);else state.pending.delete(key);document.querySelectorAll(`[data-action="${key}"]`).forEach(button=>button.disabled=pending)}
async function action(name,extra={}){const target=state.snapshot?.players.find(player=>player.token===state.selectedToken);if(['kill-room','heal-player','kick-player'].includes(name)&&!target){toast('Önce bir oyuncu seçin.',true);return false}const confirmations={
  'kill-room':`${target?.name} oyuncusunun bulunduğu ${target?.level} / ${target?.roomId} odasındaki tüm düşmanlar öldürülsün mü?`,
  'kick-player':`${target?.name} oyuncusunun bağlantısı kesilsin mi?`
};if(confirmations[name]&&!await confirmAction(confirmations[name],name==='kick-player'?'Bağlantıyı kes':'Odayı temizle'))return false;if(state.pending.has(name))return false;setPending(name,true);try{const result=await api('action',{method:'POST',body:JSON.stringify({action:name,token:target?.token,roomId:target?.roomId,...extra})});toast(name==='kill-room'?`${result.defeated} düşman öldürüldü.`:'İşlem tamamlandı.');return true}catch(error){toast(error.message,true);return false}finally{setPending(name,false)}}
document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>action(button.dataset.action)));
['oneHitEnabled','godModeEnabled','freezeEnemies'].forEach(key=>$(key).addEventListener('change',()=>state.settingsDirty=true));
$('saveSettings').addEventListener('click',async()=>{if(state.pending.has('settings'))return;state.pending.add('settings');$('saveSettings').disabled=true;try{const payload=readSettings();await api('settings',{method:'PATCH',body:JSON.stringify(payload)});state.settingsDirty=false;if(state.snapshot)state.snapshot.settings={...state.snapshot.settings,...payload};toast('Runtime ayarları uygulandı.')}catch(error){toast(error.message,true)}finally{state.pending.delete('settings');$('saveSettings').disabled=false}});
$('resetSettings').addEventListener('click',async()=>{if(!await confirmAction('Tüm runtime oyun kuralları varsayılan değerlere döndürülsün mü?','Ayarları sıfırla'))return;$('resetSettings').disabled=true;try{const result=await api('reset',{method:'POST',body:'{}'});syncSettings(result.settings);toast('Ayarlar varsayılana döndü.')}catch(error){toast(error.message,true)}finally{$('resetSettings').disabled=false}});
$('announceForm').addEventListener('submit',async event=>{event.preventDefault();const input=$('announcement');const message=input.value.trim();if(!message)return;const submit=event.submitter;submit.disabled=true;const sent=await action('announce',{message});submit.disabled=false;if(sent)input.value='';else input.focus()});
function updateNavigation(){const hash=location.hash||'#overview';document.querySelectorAll('.nav-item').forEach(link=>{const active=link.getAttribute('href')===hash;link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current')})}
window.addEventListener('hashchange',updateNavigation);updateNavigation();initSliders();initMetrics();const events=new EventSource('/events');events.addEventListener('snapshot',event=>{try{render(JSON.parse(event.data))}catch(error){toast(error.message,true)}});events.onerror=()=>{$('liveDot').className='dot error';$('liveText').textContent='Bağlantı kesildi';$('lastUpdate').textContent='Yeniden deneniyor…'};$('refreshView').addEventListener('click',()=>{if(state.snapshot){render(state.snapshot);toast('Görünüm yenilendi.')}else toast('Canlı sunucu bağlantısı bekleniyor.',true)});
